export const actions = {
  ADD_ALL_MONSTERS: "ADD_ALL_MONSTERS",
  ADD_MONSTER: "ADD_MONSTER",
  ADD_ENCOUNTER: "ADD_ENCOUNTER",
  SET_SELECTED_ENCOUNTER: "SET_SELECTED_ENCOUNTER",
  SET_SELECTED_ENCOUNTER_CREATURES: "SET_SELECTED_ENCOUNTER_CREATURES",
  SET_HEALTH: "SET_HEALTH",
  SET_GROUP_INITIATIVE_SELECTOR: "SET_GROUP_INITIATIVE_SELECTOR",
};
